apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: browser-cluster
  namespace: ray-system
spec:
  rayClusterConfig:
    rayVersion: '2.47.1'
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
        num-cpus: "0"
      template:
        spec:
          containers:
          - name: ray-head
            image: browserstation:v1.0
            env:
            - name: RAY_memory_usage_threshold
              value: "0.95"
            ports:
            - containerPort: 8050
              name: http
            command: ["/bin/bash", "-c", "ray start --head --port=6379 --dashboard-host=0.0.0.0 --metrics-export-port=8080 --num-cpus=0 --block & sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8050"]
    
    workerGroupSpecs:
    - groupName: browser-workers
      replicas: 6
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-worker
            image: browserstation:v1.0
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
          - name: chrome
            image: zenika/alpine-chrome:100
            securityContext:
              runAsUser: 0
              runAsNonRoot: false
            args:
            - --no-sandbox
            - --remote-debugging-address=0.0.0.0
            - --remote-debugging-port=9222
            ports:
            - containerPort: 9222
              name: devtools
              # Absolute cpu/memory limit for the worker
            resources:
              requests:
                cpu: "900m"
                memory: "768Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: browser-cluster-public
  namespace: ray-system
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kuberay
    ray.io/node-type: head
  ports:
  - name: serve
    port: 8050
    targetPort: 8050